#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;

$root = $wykonaj;

$wykonaj = $dodaj | $usuń | $sprawdź | $edytuj | przełóż {przełóż} | zakończ {zakończ};

$dodaj = (dodaj | utwórz | dorzuć | stwórz | zrób | wpisz | wrzuć | zapisz) {dodaj};

$usuń = (usuń | anuluj | wyrzuć | odwołaj | skasuj | zlikwiduj | skreśl) {usuń};

$sprawdź = (sprawdź | odczytaj | przeczytaj | powiedz) {sprawdź};

$edytuj = (edytuj | zmień | przetwórz | zredaguj | redaguj) {edytuj};

$zakończ = zakończ {zakończ};
